// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/cluster/v1/cluster.proto

package clusterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Affiliate represents a cluster member containing an ID, encrypted data payload,
// and encrypted endpoint list.
type Affiliate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Endpoints     []byte                 `protobuf:"bytes,3,opt,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Affiliate) Reset() {
	*x = Affiliate{}
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Affiliate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Affiliate) ProtoMessage() {}

func (x *Affiliate) ProtoReflect() protoreflect.Message {
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Affiliate.ProtoReflect.Descriptor instead.
func (*Affiliate) Descriptor() ([]byte, []int) {
	return file_api_cluster_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *Affiliate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Affiliate) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Affiliate) GetEndpoints() []byte {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

// HelloRequest initiates the client handshake.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ClientVersion string                 `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_api_cluster_v1_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *HelloRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *HelloRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

// HelloResponse returns connection information to the client.
type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientIp      string                 `protobuf:"bytes,1,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Redirect      *Endpoint              `protobuf:"bytes,2,opt,name=redirect,proto3" json:"redirect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_api_cluster_v1_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *HelloResponse) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *HelloResponse) GetRedirect() *Endpoint {
	if x != nil {
		return x.Redirect
	}
	return nil
}

// Endpoint specifies a network endpoint.
type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_api_cluster_v1_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *Endpoint) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

// AffiliateUpdateRequest submits affiliate updates with optional data and endpoints.
type AffiliateUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	AffiliateId   string                 `protobuf:"bytes,2,opt,name=affiliate_id,json=affiliateId,proto3" json:"affiliate_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Endpoints     []byte                 `protobuf:"bytes,4,opt,name=endpoints,proto3" json:"endpoints,omitempty"`
	Ttl           *durationpb.Duration   `protobuf:"bytes,5,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AffiliateUpdateRequest) Reset() {
	*x = AffiliateUpdateRequest{}
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AffiliateUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffiliateUpdateRequest) ProtoMessage() {}

func (x *AffiliateUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffiliateUpdateRequest.ProtoReflect.Descriptor instead.
func (*AffiliateUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_cluster_v1_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *AffiliateUpdateRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *AffiliateUpdateRequest) GetAffiliateId() string {
	if x != nil {
		return x.AffiliateId
	}
	return ""
}

func (x *AffiliateUpdateRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AffiliateUpdateRequest) GetEndpoints() []byte {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *AffiliateUpdateRequest) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

// AffiliateUpdateResponse confirms the update operation.
type AffiliateUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AffiliateUpdateResponse) Reset() {
	*x = AffiliateUpdateResponse{}
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AffiliateUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffiliateUpdateResponse) ProtoMessage() {}

func (x *AffiliateUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffiliateUpdateResponse.ProtoReflect.Descriptor instead.
func (*AffiliateUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_cluster_v1_cluster_proto_rawDescGZIP(), []int{5}
}

// AffiliateDeleteRequest specifies affiliate removal by cluster and affiliate ID.
type AffiliateDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	AffiliateId   string                 `protobuf:"bytes,2,opt,name=affiliate_id,json=affiliateId,proto3" json:"affiliate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AffiliateDeleteRequest) Reset() {
	*x = AffiliateDeleteRequest{}
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AffiliateDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffiliateDeleteRequest) ProtoMessage() {}

func (x *AffiliateDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffiliateDeleteRequest.ProtoReflect.Descriptor instead.
func (*AffiliateDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_cluster_v1_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *AffiliateDeleteRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *AffiliateDeleteRequest) GetAffiliateId() string {
	if x != nil {
		return x.AffiliateId
	}
	return ""
}

// AffiliateDeleteResponse confirms the deletion operation.
type AffiliateDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AffiliateDeleteResponse) Reset() {
	*x = AffiliateDeleteResponse{}
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AffiliateDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffiliateDeleteResponse) ProtoMessage() {}

func (x *AffiliateDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffiliateDeleteResponse.ProtoReflect.Descriptor instead.
func (*AffiliateDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_cluster_v1_cluster_proto_rawDescGZIP(), []int{7}
}

// ListRequest queries cluster affiliates.
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_cluster_v1_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *ListRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// ListResponse returns all affiliates for the cluster.
type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Affiliates    []*Affiliate           `protobuf:"bytes,1,rep,name=affiliates,proto3" json:"affiliates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_cluster_v1_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *ListResponse) GetAffiliates() []*Affiliate {
	if x != nil {
		return x.Affiliates
	}
	return nil
}

// WatchRequest initiates monitoring of cluster changes.
type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_api_cluster_v1_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *WatchRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// WatchResponse streams affiliate changes with a deletion flag.
type WatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Affiliate     *Affiliate             `protobuf:"bytes,1,opt,name=affiliate,proto3" json:"affiliate,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_cluster_v1_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_api_cluster_v1_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *WatchResponse) GetAffiliate() *Affiliate {
	if x != nil {
		return x.Affiliate
	}
	return nil
}

func (x *WatchResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_api_cluster_v1_cluster_proto protoreflect.FileDescriptor

const file_api_cluster_v1_cluster_proto_rawDesc = "" +
	"\n" +
	"\x1capi/cluster/v1/cluster.proto\x12\x17sidero.discovery.server\x1a\x1egoogle/protobuf/duration.proto\"M\n" +
	"\tAffiliate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1c\n" +
	"\tendpoints\x18\x03 \x01(\fR\tendpoints\"T\n" +
	"\fHelloRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\"k\n" +
	"\rHelloResponse\x12\x1b\n" +
	"\tclient_ip\x18\x01 \x01(\tR\bclientIp\x12=\n" +
	"\bredirect\x18\x02 \x01(\v2!.sidero.discovery.server.EndpointR\bredirect\"\x1e\n" +
	"\bEndpoint\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\"\xb9\x01\n" +
	"\x16AffiliateUpdateRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12!\n" +
	"\faffiliate_id\x18\x02 \x01(\tR\vaffiliateId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1c\n" +
	"\tendpoints\x18\x04 \x01(\fR\tendpoints\x12+\n" +
	"\x03ttl\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"\x19\n" +
	"\x17AffiliateUpdateResponse\"Z\n" +
	"\x16AffiliateDeleteRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12!\n" +
	"\faffiliate_id\x18\x02 \x01(\tR\vaffiliateId\"\x19\n" +
	"\x17AffiliateDeleteResponse\",\n" +
	"\vListRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"R\n" +
	"\fListResponse\x12B\n" +
	"\n" +
	"affiliates\x18\x01 \x03(\v2\".sidero.discovery.server.AffiliateR\n" +
	"affiliates\"-\n" +
	"\fWatchRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"k\n" +
	"\rWatchResponse\x12@\n" +
	"\taffiliate\x18\x01 \x01(\v2\".sidero.discovery.server.AffiliateR\taffiliate\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\bR\adeleted2\xfc\x03\n" +
	"\aCluster\x12V\n" +
	"\x05Hello\x12%.sidero.discovery.server.HelloRequest\x1a&.sidero.discovery.server.HelloResponse\x12t\n" +
	"\x0fAffiliateUpdate\x12/.sidero.discovery.server.AffiliateUpdateRequest\x1a0.sidero.discovery.server.AffiliateUpdateResponse\x12t\n" +
	"\x0fAffiliateDelete\x12/.sidero.discovery.server.AffiliateDeleteRequest\x1a0.sidero.discovery.server.AffiliateDeleteResponse\x12S\n" +
	"\x04List\x12$.sidero.discovery.server.ListRequest\x1a%.sidero.discovery.server.ListResponse\x12X\n" +
	"\x05Watch\x12%.sidero.discovery.server.WatchRequest\x1a&.sidero.discovery.server.WatchResponse0\x01B@Z>github.com/mpepping/discovery-service/api/cluster/v1;clusterv1b\x06proto3"

var (
	file_api_cluster_v1_cluster_proto_rawDescOnce sync.Once
	file_api_cluster_v1_cluster_proto_rawDescData []byte
)

func file_api_cluster_v1_cluster_proto_rawDescGZIP() []byte {
	file_api_cluster_v1_cluster_proto_rawDescOnce.Do(func() {
		file_api_cluster_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_cluster_v1_cluster_proto_rawDesc), len(file_api_cluster_v1_cluster_proto_rawDesc)))
	})
	return file_api_cluster_v1_cluster_proto_rawDescData
}

var file_api_cluster_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_cluster_v1_cluster_proto_goTypes = []any{
	(*Affiliate)(nil),               // 0: sidero.discovery.server.Affiliate
	(*HelloRequest)(nil),            // 1: sidero.discovery.server.HelloRequest
	(*HelloResponse)(nil),           // 2: sidero.discovery.server.HelloResponse
	(*Endpoint)(nil),                // 3: sidero.discovery.server.Endpoint
	(*AffiliateUpdateRequest)(nil),  // 4: sidero.discovery.server.AffiliateUpdateRequest
	(*AffiliateUpdateResponse)(nil), // 5: sidero.discovery.server.AffiliateUpdateResponse
	(*AffiliateDeleteRequest)(nil),  // 6: sidero.discovery.server.AffiliateDeleteRequest
	(*AffiliateDeleteResponse)(nil), // 7: sidero.discovery.server.AffiliateDeleteResponse
	(*ListRequest)(nil),             // 8: sidero.discovery.server.ListRequest
	(*ListResponse)(nil),            // 9: sidero.discovery.server.ListResponse
	(*WatchRequest)(nil),            // 10: sidero.discovery.server.WatchRequest
	(*WatchResponse)(nil),           // 11: sidero.discovery.server.WatchResponse
	(*durationpb.Duration)(nil),     // 12: google.protobuf.Duration
}
var file_api_cluster_v1_cluster_proto_depIdxs = []int32{
	3,  // 0: sidero.discovery.server.HelloResponse.redirect:type_name -> sidero.discovery.server.Endpoint
	12, // 1: sidero.discovery.server.AffiliateUpdateRequest.ttl:type_name -> google.protobuf.Duration
	0,  // 2: sidero.discovery.server.ListResponse.affiliates:type_name -> sidero.discovery.server.Affiliate
	0,  // 3: sidero.discovery.server.WatchResponse.affiliate:type_name -> sidero.discovery.server.Affiliate
	1,  // 4: sidero.discovery.server.Cluster.Hello:input_type -> sidero.discovery.server.HelloRequest
	4,  // 5: sidero.discovery.server.Cluster.AffiliateUpdate:input_type -> sidero.discovery.server.AffiliateUpdateRequest
	6,  // 6: sidero.discovery.server.Cluster.AffiliateDelete:input_type -> sidero.discovery.server.AffiliateDeleteRequest
	8,  // 7: sidero.discovery.server.Cluster.List:input_type -> sidero.discovery.server.ListRequest
	10, // 8: sidero.discovery.server.Cluster.Watch:input_type -> sidero.discovery.server.WatchRequest
	2,  // 9: sidero.discovery.server.Cluster.Hello:output_type -> sidero.discovery.server.HelloResponse
	5,  // 10: sidero.discovery.server.Cluster.AffiliateUpdate:output_type -> sidero.discovery.server.AffiliateUpdateResponse
	7,  // 11: sidero.discovery.server.Cluster.AffiliateDelete:output_type -> sidero.discovery.server.AffiliateDeleteResponse
	9,  // 12: sidero.discovery.server.Cluster.List:output_type -> sidero.discovery.server.ListResponse
	11, // 13: sidero.discovery.server.Cluster.Watch:output_type -> sidero.discovery.server.WatchResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_cluster_v1_cluster_proto_init() }
func file_api_cluster_v1_cluster_proto_init() {
	if File_api_cluster_v1_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_cluster_v1_cluster_proto_rawDesc), len(file_api_cluster_v1_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_cluster_v1_cluster_proto_goTypes,
		DependencyIndexes: file_api_cluster_v1_cluster_proto_depIdxs,
		MessageInfos:      file_api_cluster_v1_cluster_proto_msgTypes,
	}.Build()
	File_api_cluster_v1_cluster_proto = out.File
	file_api_cluster_v1_cluster_proto_goTypes = nil
	file_api_cluster_v1_cluster_proto_depIdxs = nil
}
